-- ============================================================================
-- step-q4b-field-notes-import.sql — Import field notes from Integrate schema
-- DO NOT RUN — apply through Supabase SQL Editor after review
-- Run order: after step-q4-field-notes.sql
-- ============================================================================

-- Generated by: node scripts/import-field-notes.mjs
-- Source: docs/integrate-drawingboard-schema.txt
-- Date: 2026-10-06
-- Entries: 26 imported, 8 skipped (empty after cleaning)

BEGIN;

UPDATE public.default_field_definitions
  SET info_note = '0 = solid timber panel with no insulation
Insulation is subtracted from panel thickness for timber volume and weight calculation.'
  WHERE field_key = 'panelPart.insulationThickness';

UPDATE public.default_field_definitions
  SET info_note = 'Cill Back Depth — Depth of cill under frame without nosing. Setting this value to -1, will dynamically set the cill back depth to the value of the frame depth'
  WHERE field_key = 'cillPart.cillBackDepth';

UPDATE public.default_field_definitions
  SET info_note = 'Cill Depth — Cill depth is total cill dimension from front to back, cill back + nosing'
  WHERE field_key = 'assemblyFramePart.cillDepth';

UPDATE public.default_field_definitions
  SET info_note = 'Mullion Stop Size — Stop sizes are dynamically labelled on the drawingboard based on the jamb type specified on the frame. The table belows shows the labels for each jamb type.Jamb TypeProperty Label<td'
  WHERE field_key = 'mullionPart.mullionStopSize';

UPDATE public.default_field_definitions
  SET info_note = 'Thickness for sashes or door leaves are set on those parts using defaultMuntinThickness property. They cannot be edited on mullion parts'
  WHERE field_key = 'mullionPart.thicknessInSash';

UPDATE public.default_field_definitions
  SET info_note = 'Transom Top Stop Size — Stop sizes are dynamically labelled on the drawingboard based on the jamb type specified on the frame. The table belows shows the labels for each jamb type.Jamb TypeProperty Label<tr'
  WHERE field_key = 'transomPart.transomStopSizeTop';

UPDATE public.default_field_definitions
  SET info_note = 'Transom Bottom Stop Size — Stop sizes are dynamically labelled on the drawingboard based on the jamb type specified on the frame. The table belows shows the labels for each jamb type.Jamb TypeProperty Label'
  WHERE field_key = 'transomPart.transomStopSizeBottom';

UPDATE public.default_field_definitions
  SET info_note = 'Thickness for sashes or door leaves are set on those parts using defaultMuntinThickness property. They cannot be edited on transom parts'
  WHERE field_key = 'transomPart.thicknessInSash';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'casementSashPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'casementSashPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'doorLeafPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'doorLeafPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomSashPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomSashPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'rightFrenchCasementSashPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'rightFrenchCasementSashPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'leftFrenchCasementSashPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'leftFrenchCasementSashPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'leftFrenchDoorLeafPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'leftFrenchDoorLeafPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'rightFrenchDoorLeafPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'rightFrenchDoorLeafPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomStableDoorLeafPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomStableDoorLeafPart.bottomHeightExternal';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomFloatingTransomCasementSashPart.bottomHeight';

UPDATE public.default_field_definitions
  SET info_note = 'External Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomFloatingTransomCasementSashPart.bottomHeightExternal';

COMMIT;
