-- =============================================================================
-- step-r4-field-visibility-import.sql — Import Integrate Standard range settings
-- DO NOT RUN directly — paste into Supabase SQL Editor after review.
--
-- Run order: 2 of 2 (run after step-r1-field-visibility.sql)
--
-- Generated by: node scripts/import-field-visibility.mjs
-- Source: docs/integrate-drawingboard-schema.txt (Standard range only)
-- Target: profile code 'sash'
-- =============================================================================

BEGIN;

INSERT INTO public.field_visibility (profile_id, field_key, visibility, updated_by)
SELECT
  p.id,
  v.field_key,
  v.visibility,
  'import-field-visibility.mjs'
FROM (VALUES
  ('drawingItemPart.newFrame', 'hidden_sales'),
  ('drawingItemPart.decoration', 'hidden_survey'),
  ('drawingItemPart.isDocL', 'hidden_survey'),
  ('paintAndIronmongeryPart.cillFinish', 'hidden_survey'),
  ('paintAndIronmongeryPart.externalFinish', 'hidden_survey'),
  ('paintAndIronmongeryPart.internalFinish', 'hidden_survey'),
  ('assemblyFramePart.cillStopId', 'hidden_always'),
  ('assemblyFramePart.cillStopSize', 'hidden_always'),
  ('assemblyFramePart.frameHeadStopSize', 'hidden_always'),
  ('assemblyFramePart.frameStopId', 'hidden_always'),
  ('bottomSashPart.btmRailShapeId', 'hidden_always'),
  ('bottomSashPart.chamferedBottomRailAngle', 'hidden_always'),
  ('bottomSashPart.constantSideOnHeightCalculation', 'hidden_always'),
  ('drawingItemPart.mouldingTypeId', 'hidden_always'),
  ('drawingItemPart.partingBeadTypeId', 'hidden_always'),
  ('glassPart.glazingBeadFixId', 'hidden_always'),
  ('mullionPart.repair', 'hidden_always'),
  ('sashPairPart.mechanicalClearanceBottom', 'hidden_always'),
  ('sashPairPart.mechanicalClearanceLeft', 'hidden_always'),
  ('sashPairPart.mechanicalClearanceRight', 'hidden_always'),
  ('sashPairPart.mechanicalClearanceTop', 'hidden_always'),
  ('sashPairPart.midRailTypeId', 'hidden_always'),
  ('topSashPart.angledTopRailHeightReduction', 'hidden_always'),
  ('topSashPart.angledTopRailId', 'hidden_always'),
  ('transomPart.hasDripRail', 'hidden_always'),
  ('transomPart.isMidrail', 'hidden_always'),
  ('transomPart.repair', 'hidden_always')
) AS v(field_key, visibility)
CROSS JOIN public.default_profiles p
WHERE p.code = 'sash'
ON CONFLICT (profile_id, field_key) DO NOTHING;

COMMIT;

-- =============================================================================
-- ROLLBACK — DO NOT RUN unless reverting step R4
-- =============================================================================
-- BEGIN;
-- DELETE FROM public.field_visibility
-- WHERE profile_id = (SELECT id FROM public.default_profiles WHERE code = 'sash')
--   AND updated_by = 'import-field-visibility.mjs';
-- COMMIT;
