-- ============================================================================
-- step-q4b-field-notes-import.sql — Import field notes from Integrate schema
-- Run order: after step-q4-field-notes.sql
-- NOTE: The previous (incorrect) version of this file was already run.
--       This regenerated version is for the record only — it contains the
--       6 genuine field keys. The 20 keys from the old run that don't exist
--       in the schema are harmless (UPDATE...WHERE matches 0 rows).
-- Rollback: DELETE is safe (sets info_note back to NULL)
-- ============================================================================

-- Generated by: node scripts/import-field-notes.mjs
-- Source: docs/integrate-drawingboard-schema.txt
-- Real field keys source: supabase/migrations/ + sql/step-*.sql
-- Date: 2026-10-06
-- Imported: 6, Skipped (no field): 28, Skipped (empty): 0

BEGIN;

UPDATE public.default_field_definitions
  SET info_note = 'Mullion Stop Size — Stop sizes are dynamically labelled on the drawingboard based on the jamb type specified on the frame. The table belows shows the labels for each jamb type.'
  WHERE field_key = 'mullionPart.mullionStopSize';

UPDATE public.default_field_definitions
  SET info_note = 'Thickness for sashes or door leaves are set on those parts using defaultMuntinThickness property. They cannot be edited on mullion parts'
  WHERE field_key = 'mullionPart.thicknessInSash';

UPDATE public.default_field_definitions
  SET info_note = 'Transom Top Stop Size — Stop sizes are dynamically labelled on the drawingboard based on the jamb type specified on the frame. The table belows shows the labels for each jamb type.'
  WHERE field_key = 'transomPart.transomStopSizeTop';

UPDATE public.default_field_definitions
  SET info_note = 'Transom Bottom Stop Size — Stop sizes are dynamically labelled on the drawingboard based on the jamb type specified on the frame. The table belows shows the labels for each jamb type.'
  WHERE field_key = 'transomPart.transomStopSizeBottom';

UPDATE public.default_field_definitions
  SET info_note = 'Thickness for sashes or door leaves are set on those parts using defaultMuntinThickness property. They cannot be edited on transom parts'
  WHERE field_key = 'transomPart.thicknessInSash';

UPDATE public.default_field_definitions
  SET info_note = 'Internal Bottom Rail Height — Calculation converts between int. & ext. based on angle and/or shape. Specify default either for int. or ext., not for both. When only the external height is set as the default be sure to set constantSideOnHeightCalculation to external_height'
  WHERE field_key = 'bottomSashPart.bottomHeight';

COMMIT;
