-- ============================================================================
-- step-p3-validation-import.sql -- Import 158 validation rules from Integrate
-- Apply through Supabase SQL Editor after review
-- Generated by: node scripts/import-validation-rules.mjs
-- ============================================================================

-- Ensure all referenced lists exist (beyond the allowed_sash_thickess seed)
INSERT INTO public.validation_lists (name, description) VALUES
  ('landvac_fineo', 'LandVac / Fineo single-pane part numbers'),
  ('6_8_acoustic', '6.8mm acoustic laminated glass part numbers'),
  ('trickle_vents', 'Trickle vent ironmongery part numbers'),
  ('timber', 'Custom off-the-shelf timber part numbers')
ON CONFLICT (name) DO NOTHING;

-- ── Rules ────────────────────────────────────────────────────────────────────

-- Rule 1: Reminder to Increase R Rumber in busy periods [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Reminder to Increase R Rumber in busy periods',
  1,
  NULL,
  'quote',
  'warning',
  'quote_margin !=1100',
  'R Number should be set to R1100 in busy periods',
  'Default to RNumber is R1000 In busy periods this should be set to R1100.',
  true,
  NULL
);

-- Rule 2: Single item fee [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Single item fee',
  10,
  NULL,
  'quote',
  'warning',
  'new_frame_qty == 0 and new_sliding_sash_qty <= 2 and item_qty == 1 and item_with_onsite_decoration_by_us_qty_excl_free_items == 0 and item_qty_with_solid_utile_hardwood_cill == 0',
  'Add a ''Single Item Fee'' free text item for single SASH REPLACEMENT projects.',
  NULL,
  true,
  NULL
);

-- Rule 3: Mixed Spacer Colour [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Mixed Spacer Colour',
  20,
  NULL,
  'quote',
  'warning',
  'max(item_qty_with_black_warm_edge_spacer, item_qty_with_white_warm_edge_spacer, item_qty_with_brown_warm_edge_spacer, item_qty_with_bronze_aluminium_spacer) < item_qty_with_black_warm_edge_spacer + item_qty_with_white_warm_edge_spacer + item_qty_with_brown_warm_edge_spacer + item_qty_with_bronze_aluminium_spacer',
  'Mixed spacer colours. Spacer colour should be amended to match all items.',
  NULL,
  true,
  NULL
);

-- Rule 4: Mixed Spacer Dimension [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Mixed Spacer Dimension',
  30,
  NULL,
  'quote',
  'warning',
  'max(item_qty_with_4mm_spacer,item_qty_with_6mm_spacer, item_qty_with_8mm_spacer, item_qty_with_10mm_spacer, item_qty_with_12mm_spacer, item_qty_with_14mm_spacer) < item_qty_with_4mm_spacer + item_qty_with_6mm_spacer + item_qty_with_8mm_spacer + item_qty_with_10mm_spacer + item_qty_with_12mm_spacer + item_qty_with_14mm_spacer + item_qty_with_16mm_spacer',
  'Mixed spacer dimensions. Spacer dimension normally matches for all items please check or amend',
  NULL,
  true,
  NULL
);

-- Rule 5: Cill Timber Not matching [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Cill Timber Not matching',
  40,
  NULL,
  'quote',
  'warning',
  'max(item_qty_with_accoya_cill,item_qty_with_oak_cill,item_qty_with_douglas_fir_cill,item_qty_with_solid_redwood_cill,item_qty_with_idigbo_cill,item_qty_with_solid_utile_hardwood_cill) < item_qty_with_accoya_cill + item_qty_with_douglas_fir_cill + item_qty_with_oak_cill + item_qty_with_solid_redwood_cill + item_qty_with_idigbo_cill + item_qty_with_solid_utile_hardwood_cill',
  'Mixed timber for cills. Cill timber normally matches for all items please check or amend',
  NULL,
  true,
  NULL
);

-- Rule 6: Installation labour hours [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Installation labour hours',
  50,
  NULL,
  'quote',
  'information',
  'item_installed_by_us_qty > 0',
  'Estimated installation hours: installation_labour_time',
  NULL,
  true,
  NULL
);

-- Rule 7: Quote PF not latest - HQ [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Quote PF not latest - HQ',
  100,
  NULL,
  'quote',
  'warning',
  'user_can_access_all_quotes and is_open_quote and not is_pricefile_retired and quote_pricefile_no < latest_pricefile_no and quote_pricefile_no > 0',
  'Quote should be updated to the latest price file.',
  NULL,
  true,
  NULL
);

-- Rule 8: Quote PF retired - HQ [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Quote PF retired - HQ',
  102,
  NULL,
  'quote',
  'warning',
  'user_can_access_all_quotes and is_open_quote and is_pricefile_retired',
  'PF quote_pricefile_no is retired. Please switch to latest live one.',
  NULL,
  true,
  NULL
);

-- Rule 9: Quote PF not latest - restricted [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Quote PF not latest - restricted',
  104,
  NULL,
  'quote',
  'warning',
  'not user_can_access_all_quotes and is_open_quote and not is_pricefile_retired and quote_pricefile_no < latest_pricefile_no and quote_pricefile_no > 0',
  'Quote should be updated to the latest price file, unless it is already a quotation presented to the customer within the validation period.',
  NULL,
  true,
  NULL
);

-- Rule 10: Quote PF retired - restricted [Quote Summary]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Quote Summary'),
  'Quote PF retired - restricted',
  106,
  NULL,
  'quote',
  'error',
  'not user_can_access_all_quotes and is_open_quote and is_pricefile_retired',
  'PF quote_pricefile_no is retired. Quote can! be published with retired price file.',
  NULL,
  true,
  NULL
);

-- Rule 11: Temp [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Temp',
  0,
  'glass_unit',
  'item',
  'warning',
  '(glass_unit_thickness == 8.3 and is_sash_arched or is_raked) and in_list( single_pane_part_no, landvac_fineo) and not is_bi_glass',
  'PLEASE ADD A QUOTE NOTE AS FOLLOWS: We are unable to order shaped vacuum insulated glass until the joinery has been manufactured and, as such, the lead time for curved vacuum insulated glazed windows will be longer than the standard lead time.',
  NULL,
  false,
  'empty list: landvac_fineo'
);

-- Rule 12: No Curved Head Sash Replacements [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'No Curved Head Sash Replacements',
  0,
  NULL,
  'item',
  'error',
  'new_sash_with_curved_head_qty > 0 and is_replacement_sashes_range',
  'We do not offer sash replacements if the sashes have a curved top rail',
  NULL,
  true,
  NULL
);

-- Rule 13: (unnamed) [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  '',
  1,
  'glass_unit',
  'item',
  'warning',
  'is_heritage and not is_filled_with_krypton',
  'Gas must be krypton in a heritage slimite unit',
  NULL,
  false,
  'product not offered'
);

-- Rule 14: Encapsulated Leaded Lights [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Encapsulated Leaded Lights',
  3,
  NULL,
  'item',
  'error',
  'encapsulated_leaded_light_qty >= 1',
  'DO NOT USE ENCAPSULATED LEADED LIGHTS. DO NOT IGNORE THIS MESSAGE. SPEAK TO CHARLIE ABOUT THIS',
  NULL,
  true,
  NULL
);

-- Rule 15: Fineo Toughened Evacuation Port [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Fineo Toughened Evacuation Port',
  4,
  NULL,
  'item',
  'information',
  'glass_unit_thickness == 9.7',
  'IF FINEO TOUGHENED IS USED, ADD QUOTE NOTE - Please note, a small visible black circular evacuation port will be visible in the corner of each unit of Fineo Toughened. We recommend viewing a sample.',
  NULL,
  true,
  NULL
);

-- Rule 16: Toughened Glass with Duplex Bars [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Toughened Glass with Duplex Bars',
  5,
  'glass_unit',
  'item',
  'information',
  'unit_gb_qty >= 1 and not is_inner_pane_toughened',
  'If plant on bars, glass must be toughened or laminated.',
  NULL,
  true,
  NULL
);

-- Rule 17: Toughened Glass with Duplex Bars [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Toughened Glass with Duplex Bars',
  6,
  'glass_unit',
  'item',
  'information',
  'unit_gb_qty >= 1 and not is_outer_pane_toughened',
  'If plant on bars, glass must be toughened or laminated.',
  NULL,
  true,
  NULL
);

-- Rule 18: Toughened Glass with Duplex Bars [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Toughened Glass with Duplex Bars',
  6,
  'glass_unit',
  'item',
  'information',
  'unit_gb_qty >= 1 and is_single_glazed and not is_single_pane_toughened',
  'Single glazed glass must be toughened or laminated.',
  NULL,
  true,
  NULL
);

-- Rule 19: Fineo under 200mm x 200mm [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Fineo under 200mm x 200mm',
  7,
  'glass_unit',
  'item',
  'error',
  'glass_unit_thickness == 7.7 and actual_width < 200',
  'FINEO MINIMUM SIZE IS 200mm x 200mm. If you can! adjust the joinery to fix the issue, add 6.8mm acoustic laminated glass in it''s place and add a Quote Note to point this out.',
  NULL,
  true,
  NULL
);

-- Rule 20: LandVac Lead Times [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'LandVac Lead Times',
  8,
  'glass_unit',
  'item',
  'warning',
  'glass_unit_thickness == 8.3',
  'ADD QUOTE NOTE - Please note, the inclusion of LandVac glass may extend our standard lead times. Please speak to the surveyor to receive estimated lead times at the time of ordering',
  NULL,
  true,
  NULL
);

-- Rule 21: Acoustic Glass in Complete New Joinery Only [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Acoustic Glass in Complete New Joinery Only',
  11,
  'glass_unit',
  'item',
  'warning',
  '(not is_complete_new) and (in_list(outer_pane_part_no, 6_8_acoustic) or in_list(inner_pane_part_no, 6_8_acoustic))',
  'Acoustic glass can only be used in complete new joinery, not sash replacements.',
  NULL,
  false,
  'empty list: 6_8_acoustic, 6_8_acoustic'
);

-- Rule 22: Acoustic Glass Spacer [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'Acoustic Glass Spacer',
  12,
  'glass_unit',
  'item',
  'warning',
  '(is_complete_new) and (( in_list( outer_pane_part_no, 6_8_acoustic) or in_list( inner_pane_part_no, 6_8_acoustic))) and spacer_dim !=14',
  'When using acoustic glass the spacer dimension needs to be set to 14.',
  NULL,
  false,
  'empty list: 6_8_acoustic, 6_8_acoustic'
);

-- Rule 23: DirGU in frame [Glass]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Glass'),
  'DirGU in frame',
  120,
  'glass_unit',
  'item',
  'warning',
  'is_direct_glazed_unit and to_be_replaced',
  'ADD QUOTE NOTE: Due to direct glazed panes, some fixing points may be situated on visible parts of the frame. These will be filled and painted once the frame is in place.',
  NULL,
  true,
  NULL
);

-- Rule 24: Sash Replacement Thickness [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Sash Replacement Thickness',
  -1,
  NULL,
  'item',
  'warning',
  'is_sw and not frame_to_be_replaced and not in_list(sash_thickness, allowed_sash_thickess)',
  'Sashes are only manufactured to 35mm, 40mm, 45mm or 50mm. Please choose a suitable thickness.',
  NULL,
  true,
  NULL
);

-- Rule 25: Lambs Tongue [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Lambs Tongue',
  0,
  NULL,
  'item',
  'error',
  'is_lambs_tongue_moulding and is_double_glazed',
  'Windows can! be made with lambs tongue moulding and double glazing. Must be either single glazing or Fineo.',
  NULL,
  true,
  NULL
);

-- Rule 26: Sash Replacement Thickness [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Sash Replacement Thickness',
  0,
  NULL,
  'item',
  'information',
  'is_sw and sash_thickness < 35 and is_double_glazed',
  'Sashes are only manufactured to 35mm',
  NULL,
  true,
  NULL
);

-- Rule 27: DSO ON SPRINGS [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'DSO ON SPRINGS',
  0,
  'sliding_sash',
  'item',
  'error',
  'is_spiral_hung and not to_be_replaced',
  'NO DRAUGHT SEAL ON SPIRAL BALANCES',
  NULL,
  true,
  NULL
);

-- Rule 28: Large Springs [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Large Springs',
  0,
  'sliding_sash',
  'item',
  'warning',
  'gross_sash_height_in_mm > 1200 and is_spiral_hung',
  'Please discuss this with Nathan. This window may be too large for spiral balances.',
  NULL,
  true,
  NULL
);

-- Rule 29: Front Door Letter Plate [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Front Door Letter Plate',
  10,
  NULL,
  'item',
  'information',
  'is_front_door and is_bolection_moulding_around_panel_internally',
  'Mullion must be at least 120mm to accommodate knocker and bolection',
  NULL,
  false,
  'missing variable: is_bolection_moulding_around_panel_internally'
);

-- Rule 30: Front Door Letter Plate [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Front Door Letter Plate',
  10,
  NULL,
  'item',
  'information',
  'is_front_door and is_bolection_moulding_around_panel_internally',
  'Midrail must be at least 175mm to accommodate letter plate and bolection',
  NULL,
  false,
  'missing variable: is_bolection_moulding_around_panel_internally'
);

-- Rule 31: 35mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '35mm Sashes DGU',
  20,
  NULL,
  'item',
  'warning',
  'sash_thickness == 35 and glass_unit_thickness > 14 and not is_single_glazed',
  '35mm sashes must have a 14mm thick DGU if STANDARD double glazed (4/6/4)',
  NULL,
  true,
  NULL
);

-- Rule 32: 35mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '35mm Sashes DGU',
  21,
  NULL,
  'item',
  'warning',
  'not is_heritage_range and sash_thickness == 35 and glass_unit_thickness < 14 and not is_single_glazed',
  '35mm sashes must have a 14mm thick DGU if STANDARD double glazed (4/6/4)',
  NULL,
  false,
  'product not offered'
);

-- Rule 33: 40mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '40mm Sashes DGU',
  22,
  NULL,
  'item',
  'warning',
  'not is_heritage_range and (sash_thickness == 40) and (glass_unit_thickness > 18) and not is_single_glazed',
  '40mm sashes must have a 18mm thick DGU if STANDARD double glazed (4/10/4)',
  NULL,
  false,
  'product not offered'
);

-- Rule 34: 40mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '40mm Sashes DGU',
  22,
  NULL,
  'item',
  'warning',
  'not is_heritage_range and (sash_thickness == 40) and (glass_unit_thickness < 18) and not is_single_glazed',
  '40mm sashes must have a 18mm thick DGU if STANDARD double glazed (4/10/4)',
  NULL,
  false,
  'product not offered'
);

-- Rule 35: 45mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '45mm Sashes DGU',
  23,
  NULL,
  'item',
  'warning',
  'not is_heritage_range and (sash_thickness == 45) and (glass_unit_thickness > 24.8 ) and not is_single_glazed',
  '45mm sashes must have a 24mm thick DGU if STANDARD double glazed (4/16/4)',
  NULL,
  false,
  'product not offered'
);

-- Rule 36: 45mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '45mm Sashes DGU',
  24,
  NULL,
  'item',
  'warning',
  'not is_heritage_range and (sash_thickness == 45) and (glass_unit_thickness < 24 ) and not is_single_glazed',
  '45mm sashes must have a 24mm thick DGU if STANDARD double glazed (4/16/4)',
  NULL,
  false,
  'product not offered'
);

-- Rule 37: 50mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '50mm Sashes DGU',
  25,
  NULL,
  'item',
  'warning',
  '(sash_thickness == 50) and (glass_unit_thickness < 28 ) and not is_single_glazed',
  '50mm sashes must have a 28mm thick DGU if STANDARD double glazed (4/20/4)',
  NULL,
  true,
  NULL
);

-- Rule 38: 50mm Sashes DGU [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  '50mm Sashes DGU',
  26,
  NULL,
  'item',
  'warning',
  '(sash_thickness == 50) and (glass_unit_thickness > 28 ) and not is_single_glazed',
  '50mm sashes must have a 28mm thick DGU if STANDARD double glazed (4/20/4)',
  NULL,
  true,
  NULL
);

-- Rule 39: Box Frame Depth [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Box Frame Depth',
  100,
  NULL,
  'item',
  'warning',
  'frame_depth < 140 and is_double_glazed and is_sw and frame_to_be_replaced',
  'Box frame depth must be 140mm to allow for double glazing',
  NULL,
  true,
  NULL
);

-- Rule 40: Sash head with trickle vent [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Sash head with trickle vent',
  110,
  'sliding_sash',
  'item',
  'error',
  'is_spiral_hung and is_complete_new and is_top_sash and contains(ironmongery_part_no_list, trickle_vents) and gross_sash_head_height_in_mm < 49',
  'Please increase top rail to 49mm to accommodate trickle vent.',
  NULL,
  false,
  'empty list: trickle_vents'
);

-- Rule 41: Sash head no trickle vent [Sash Windows]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Sash Windows'),
  'Sash head no trickle vent',
  111,
  'sliding_sash',
  'item',
  'warning',
  'is_spiral_hung and is_complete_new and is_top_sash and not contains(ironmongery_part_no_list, trickle_vents) and gross_sash_head_height_in_mm == 57',
  'Top rail can be reduced to 49mm if no trickle vent.',
  NULL,
  false,
  'empty list: trickle_vents'
);

-- Rule 42: Storm Proof Sash Replacement [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Storm Proof Sash Replacement',
  0,
  'casement_sash',
  'item',
  'error',
  'is_storm_proof and not is_complete_new',
  'We only do stormproof if it is complete replacement',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 43: Storm proof casement windows (not flush) [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Storm proof casement windows (not flush)',
  5,
  'casement_sash',
  'item',
  'warning',
  'is_storm_proof',
  'ADD QUOTE NOTE: Storm proof casement windows (not flush)',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 44: Bottom Hung Stormproof Casements [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Bottom Hung Stormproof Casements',
  10,
  'casement_sash',
  'item',
  'error',
  'is_storm_proof and is_bottom_hung',
  'Can! do bottom hung stormproof windows',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 45: Tilt and Turn Windows [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Tilt and Turn Windows',
  11,
  'casement_sash',
  'item',
  'error',
  'is_bottom_and_left_hand_hung_viewed_internally or is_bottom_and_right_hand_hung_viewed_internally',
  'We do not do multiple hung sashes',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 46: Top Hung Casement Width [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Top Hung Casement Width',
  20,
  'casement_sash',
  'item',
  'error',
  'is_storm_proof and is_top_hung and width <= 0.31',
  'Minimum sashwidth for a top hung stormproof casement is 310mm',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 47: Stormproof Heritage [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Stormproof Heritage',
  25,
  'casement_sash',
  'item',
  'error',
  'is_storm_proof and is_heritage_range',
  'Stormproof windows can! be manufactured in the heritage range',
  NULL,
  false,
  'product not offered'
);

-- Rule 48: Casement Window Bottom Rail [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Window Bottom Rail',
  100,
  'casement_sash',
  'item',
  'error',
  'not (gross_bottom_rail_height_in_mm == 93 or gross_bottom_rail_height_in_mm == 64)',
  'Flush casement window bottom rails must be either 93mm or 64mm. 64mm should only be used if the casement sash is less than 600mm wide x 600mm high',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 49: Casement Window Bottom Rail Size [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Window Bottom Rail Size',
  110,
  'casement_sash',
  'item',
  'warning',
  'width <= 0.6 and height <= 0.6 and gross_bottom_rail_height_in_mm > 64',
  'For casement sashes that are smaller than 600mm wide and 600mm high, we would advise changing the bottom rail (ext) to 64mm',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 50: Casement Frame Head [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Frame Head',
  120,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and widest_external_frame_width >= 1.2',
  'For casement frames that are wider than 1.2m, please update the Head measurement to 68mm',
  NULL,
  false,
  'missing variable: widest_external_frame_width'
);

-- Rule 51: Casement Frame Head [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Frame Head',
  125,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (frame_head_height_in_mm == 60 or frame_head_height_in_mm == 68)',
  'Casement frame head dimension should be 60mm as standard, or 68mm if it is wider than 1.2m',
  NULL,
  false,
  'missing variable: frame_head_height_in_mm'
);

-- Rule 52: Casement Frame Head [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Frame Head',
  130,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and widest_external_frame_width >= 1.2',
  'For casement frames that are wider than 1.2m, please update the Head measurement to 68mm',
  NULL,
  false,
  'missing variable: widest_external_frame_width'
);

-- Rule 53: Casement Window Top Rail [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Window Top Rail',
  135,
  'casement_sash',
  'item',
  'error',
  'not (gross_sash_head_height_in_mm == 64)',
  'Top rails on casement windows must always be 64mm',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 54: Casement Window Stiles [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Window Stiles',
  140,
  'casement_sash',
  'item',
  'error',
  'not is_french_casement_sash and not (gross_left_sash_stile_width_in_mm == 64) or not gross_right_sash_stile_width_in_mm == 64',
  '1-Stiles on casement windows must always be 64mm',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 55: Casement Frame Jambs [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Frame Jambs',
  145,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (frame_jamb_left == 60)',
  'Casement frame jambs must be 60mm (non-profiled). If additional timber is needed to make up larger frame sections, please add this on Finish & Ironmongery>Component>Other',
  NULL,
  false,
  'missing variable: frame_jamb_left'
);

-- Rule 56: Casement Machined Out (Left) [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Machined Out (Left)',
  150,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (frame_jamb_profiled_left + 18 == frame_jamb_left)',
  'For all casement windows, the Machined Out from Jamb measurement must be 18',
  NULL,
  false,
  'missing variable: frame_jamb_profiled_left, frame_jamb_left'
);

-- Rule 57: Casement Machined Out (Right) [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Machined Out (Right)',
  155,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (frame_jamb_profiled_right + 18 == frame_jamb_right)',
  'For all casement windows, the Machined Out from Jamb measurement must be 18',
  NULL,
  false,
  'missing variable: frame_jamb_profiled_right, frame_jamb_right'
);

-- Rule 58: Casement Machined Out (Head) [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Machined Out (Head)',
  160,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (frame_head_profiled_height_in_mm + 18 == frame_head_height_in_mm)',
  'For all casement windows, the Machined Out from Head measurement must be 18',
  NULL,
  false,
  'missing variable: frame_head_profiled_height_in_mm, frame_head_height_in_mm'
);

-- Rule 59: Casement Sash Thickness [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Sash Thickness',
  165,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (sash_thickness == 57)',
  'Casement sashes where the frame is being replaced must be 57mm thick',
  NULL,
  true,
  NULL
);

-- Rule 60: Casement Frame Thickness [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Casement Frame Thickness',
  170,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_to_be_replaced and not (frame_depth == 93)',
  'Casement frame depth must be 93mm',
  NULL,
  true,
  NULL
);

-- Rule 61: Mullion Size [Stormproof Casements]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Stormproof Casements'),
  'Mullion Size',
  175,
  NULL,
  'item',
  'error',
  'is_casement_window and frame_mullion_qty >= 1 and not (frame_mullion_to_be_replaced_width == 32)',
  'Frame mullion (profiled) must be 32mm',
  NULL,
  false,
  'missing variable: frame_mullion_to_be_replaced_width'
);

-- Rule 62: Building Site Installation Level [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Building Site Installation Level',
  1,
  NULL,
  'item',
  'warning',
  'is_installation_level_test_1',
  'ADD QUOTE NOTE - Building site installation level included. Please refer to the customer information document for more details.',
  NULL,
  false,
  'missing variable: is_installation_level_test_1'
);

-- Rule 63: Building Site Installation Level Customer Info Sheet [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Building Site Installation Level Customer Info Sheet',
  1,
  NULL,
  'item',
  'warning',
  'is_installation_level_test_1',
  'Building site installation level included. Please ensure the customer receives the info sheet and understands this has been included on the quote.',
  NULL,
  false,
  'missing variable: is_installation_level_test_1'
);

-- Rule 64: Frame depth 0 [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Frame depth 0',
  10,
  NULL,
  'item',
  'error',
  'frame_depth == 0 and frame_to_be_replaced',
  'Frame depth can! be 0mm',
  NULL,
  true,
  NULL
);

-- Rule 65: Cill depth 0 [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Cill depth 0',
  20,
  NULL,
  'item',
  'error',
  'cill_depth == 0 and frame_to_be_replaced',
  'Cill depth can! be 0mm',
  NULL,
  true,
  NULL
);

-- Rule 66: No surveyor [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'No surveyor',
  30,
  NULL,
  'item',
  'error',
  'is_survey_drawing and not is_surveyor_specified',
  'Surveyor not specified',
  NULL,
  true,
  NULL
);

-- Rule 67: Fit in van [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Fit in van',
  40,
  NULL,
  'item',
  'warning',
  'is_complete_new and not is_frame_in_kit_form and max(widest_external_frame_width, tallest_external_frame_height) > 2.7 and min(widest_external_frame_width, tallest_external_frame_height) > 2',
  'Frame does not fit in standard van. Add 100 POA for Luton',
  NULL,
  false,
  'missing variable: widest_external_frame_width, tallest_external_frame_height'
);

-- Rule 68: No surrounds [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'No surrounds',
  50,
  NULL,
  'item',
  'information',
  'is_complete_new and is_installation_included and surround_row_qty == 0',
  'Complete new item without surrounds',
  NULL,
  true,
  NULL
);

-- Rule 69: Sash Replacement Surrounds [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Sash Replacement Surrounds',
  51,
  NULL,
  'item',
  'information',
  'is_installation_included and surround_row_qty >= 1 and not is_complete_new',
  'Non-frame replacement with surrounds',
  NULL,
  true,
  NULL
);

-- Rule 70: Unmodified default [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Unmodified default',
  60,
  NULL,
  'item',
  'warning',
  'has_unmodified_default_measurement',
  'Default measurement(s) not modified (unmodified_default_measurement_text)',
  'Dimension ends in 99',
  true,
  NULL
);

-- Rule 71: Paint empty [Missing Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Missing Detail'),
  'Paint empty',
  70,
  NULL,
  'item',
  'warning',
  'empty(internal_finish) or empty(external_finish)',
  'Paint finish missing',
  NULL,
  true,
  NULL
);

-- Rule 72: Bifold Door Weight [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Bifold Door Weight',
  0,
  NULL,
  'item',
  'error',
  'is_bi_fold_door_set and weight_of_heaviest_sash_to_be_replaced > 220',
  'Maximum weight for a bifolding door leaf is 100kg. This door leaf exceeds this and can! be made.',
  NULL,
  false,
  'missing variable: is_bi_fold_door_set, weight_of_heaviest_sash_to_be_replaced'
);

-- Rule 73: CASEMENT SASH WIDTH [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'CASEMENT SASH WIDTH',
  0,
  'casement_sash',
  'item',
  'error',
  'width < 0.3',
  'We can! manufacture casement sashes narrower than 300mm as it is unsafe on the spindle moulder',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 74: CASEMENT SASH HEIGHT [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'CASEMENT SASH HEIGHT',
  0,
  'casement_sash',
  'item',
  'error',
  'height < 0.3',
  'We can! manufacture casement sashes narrower than 300mm as it is unsafe on the spindle moulder',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 75: Fanlight bottom rail [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Fanlight bottom rail',
  1,
  'casement_sash',
  'item',
  'warning',
  'is_fanlight and to_be_replaced and gross_bottom_rail_height_in_mm > 62',
  'Fanlight bottom rail should be reduced to 62mm externally',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 76: Equal glazing is out [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Equal glazing is out',
  10,
  NULL,
  'item',
  'warning',
  'new_sash_qty > 0 and eq_glazing_is_out',
  'Equal glazing is out, check sightline sizes',
  NULL,
  true,
  NULL
);

-- Rule 77: Restricted sash travel [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Restricted sash travel',
  20,
  NULL,
  'item',
  'warning',
  'sliding_sash_with_restricted_travel_qty > 0',
  'Restricted sash travel for sliding_sash_with_restricted_travel_qty sash(es)',
  NULL,
  true,
  NULL
);

-- Rule 78: Toughened too small [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Toughened too small',
  30,
  'glass_unit',
  'item',
  'error',
  'is_heritage and actual_width < 100 or is_heritage and actual_height < 100',
  'Toughened glass too small to manufacture, minimum size for heritage toughened units is 100mm x 100mm. If joinery can! be adjusted to suit, add non toughened glass if possible. If not, speak to manager.',
  NULL,
  false,
  'product not offered'
);

-- Rule 79: Toughened too small [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Toughened too small',
  35,
  'glass_unit',
  'item',
  'error',
  'actual_area < 0.05 and not is_heritage and (is_inner_pane_toughened or is_outer_pane_toughened)',
  'Toughened glass too small to manufacture, minimum size is 250mm x 250mm. If joinery can! be adjusted to suit, add non toughened glass/laminated glass.',
  NULL,
  false,
  'product not offered'
);

-- Rule 80: Frame deeper than cill [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Frame deeper than cill',
  40,
  NULL,
  'item',
  'error',
  'new_frame_qty > 0 and cill_height > 1 and cill_depth < frame_depth',
  'Frame can! be deeper than cill',
  NULL,
  true,
  NULL
);

-- Rule 81: Multipoint Doors too Tall [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Multipoint Doors too Tall',
  50,
  'door_leaf',
  'item',
  'error',
  'is_door_mpls and height >= 3.067',
  'Door leaf is too high for standard multipoint lock. Contact Nathan for assistance',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 82: Multipoint Doors to Short [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Multipoint Doors to Short',
  55,
  'door_leaf',
  'item',
  'error',
  'is_door_mpls and height < 1.853',
  'Door leaf is too short for standard multipoint lock. Contact Nathan for assistance',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 83: Softwood Over 100mm Thickness [Dimension]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Dimension'),
  'Softwood Over 100mm Thickness',
  100,
  NULL,
  'item',
  'error',
  'is_solid_softwood_pine_frame and frame_depth > 100',
  'Softwood should not be used in sections greater than 100mm. Must be hardwood.',
  NULL,
  false,
  'missing variable: is_solid_softwood_pine_frame'
);

-- Rule 84: Fineo HOARG vs BiGlass [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Fineo HOARG vs BiGlass',
  0,
  NULL,
  'item',
  'error',
  'hoarg_qty > 0 and glass_unit_thickness == 7.7',
  'Fineo glass replacement into existing is bi-glass',
  NULL,
  false,
  'missing variable: hoarg_qty'
);

-- Rule 85: Oak [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Oak',
  0,
  NULL,
  'item',
  'warning',
  'is_oak_cill or is_oak_cill or is_oak_sash',
  'Please note, we advise against using oak for external joinery. It is very prone to discolouration and movement. We offer no guarantee against this. We recommend using idigbo wood as an oak alternative. For more information on this please speak to your surveyor.',
  NULL,
  true,
  NULL
);

-- Rule 86: Softwood Cill [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Softwood Cill',
  0,
  NULL,
  'item',
  'error',
  'is_solid_redwood_cill',
  'Softwood cills are not permitted. Please change to hardwood',
  NULL,
  true,
  NULL
);

-- Rule 87: Front Door [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Front Door',
  0,
  NULL,
  'item',
  'warning',
  'is_front_door',
  'Please check the customer is happy with the hinge side. Most customers do not think to check this so please check that what you have drawn matches the existing, or if it does not, make it clear that it is different to existing both in the quote notes and in an email.',
  NULL,
  true,
  NULL
);

-- Rule 88: Opening out front door [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Opening out front door',
  10,
  NULL,
  'item',
  'warning',
  'is_front_door and opening_out_door_leaf_qty > 0',
  'Opening out front door',
  NULL,
  false,
  'missing variable: opening_out_door_leaf_qty'
);

-- Rule 89: Frame interior widths off [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Frame interior widths off',
  20,
  NULL,
  'item',
  'warning',
  'frame_interior_widths_are_slightly_off',
  'Frame interior widths are similar but not the same',
  NULL,
  false,
  'missing variable: frame_interior_widths_are_slightly_off'
);

-- Rule 90: Single Glazed Item [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Single Glazed Item',
  30,
  NULL,
  'item',
  'warning',
  'is_single_glazed and frame_to_be_replaced and is_docl and not glass_unit_thickness == 7.7',
  'Single glazing in complete replacement is not building reg compliant. Ensure Doc L is unticked',
  NULL,
  true,
  NULL
);

-- Rule 91: DOCL Heritage [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'DOCL Heritage',
  35,
  NULL,
  'item',
  'warning',
  'glass_unit_thickness <= 18 and frame_to_be_replaced and is_docl and glass_unit_qty >= 1 and is_double_glazed',
  'DOC L? This item may not be not building reg compliant. If the glazing does not have a centre pane U-value of 1.4 or less, Ensure Doc L is unticked',
  NULL,
  true,
  NULL
);

-- Rule 92: DOCL Single [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'DOCL Single',
  36,
  NULL,
  'item',
  'warning',
  'frame_to_be_replaced and is_docl and glass_unit_qty >= 1 and is_single_glazed and glass_unit_thickness < 7',
  'DOC L? This item may not be not building reg compliant. If the glazing does not have a centre pane U-value of 1.4 or less, Ensure Doc L is unticked',
  NULL,
  true,
  NULL
);

-- Rule 93: Raked Frame [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Raked Frame',
  200,
  NULL,
  'item',
  'warning',
  'has_raked_frame',
  'PLEASE NOTE THAT THE SYSTEM DOES NOT PRICE FOR RAKED FRAMES. SPEAK TO CHARLIE TO GET A POA',
  NULL,
  false,
  'missing variable: has_raked_frame'
);

-- Rule 94: Inward Opening Bifold [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Inward Opening Bifold',
  210,
  NULL,
  'item',
  'error',
  'is_bi_fold_door_set and opening_in_door_leaf_qty >= 1',
  'WE DO NOT OFFER OPENING IN BIFOLDING DOORS',
  NULL,
  false,
  'missing variable: is_bi_fold_door_set, opening_in_door_leaf_qty'
);

-- Rule 95: Bifold hEIGHT [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Bifold hEIGHT',
  215,
  'door_leaf',
  'item',
  'error',
  'is_folding_leaf and gross_sash_head_height_in_mm >= 2700',
  'MAX DOOR HEIGHT FOR BIFOLDING DOORS IS 2700MM',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 96: BIFOLD WIDTH [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'BIFOLD WIDTH',
  220,
  'door_leaf',
  'item',
  'error',
  'is_folding_leaf and gross_sash_width_in_mm >= 1100',
  'MAX DOOR WIDTH FOR BIFOLDING DOORS IS 1100MM',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 97: Ali Threshold Over 3m [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Ali Threshold Over 3m',
  250,
  NULL,
  'item',
  'error',
  'is_aluminium_cill and overall_frame_width_in_mm > 3000',
  'An aluminium cill does not come in lengths over 3m and it is not advised for it to be jointed together.',
  NULL,
  false,
  'missing variable: is_aluminium_cill, overall_frame_width_in_mm'
);

-- Rule 98: Replacement sash not allowed in heritage range (complete new windows only) [Suspicious Detail]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Suspicious Detail'),
  'Replacement sash not allowed in heritage range (complete new windows only)',
  251,
  NULL,
  'item',
  'warning',
  'not is_complete_new and is_heritage_range',
  'Replacement sash can! be drawn in Heritage range unless they are 45mm thick',
  NULL,
  false,
  'product not offered'
);

-- Rule 99: TEST [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'TEST',
  -106,
  'component',
  'item',
  'warning',
  'in_list(part_no, timber)',
  'If you are specifying custom off the shelf timber, please ensure that you include the link in the notes of the component and add a price POA',
  NULL,
  false,
  'part type not built yet: component'
);

-- Rule 100: Trickle Vent part_no [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Trickle Vent part_no',
  -104,
  NULL,
  'item',
  'warning',
  'frame_to_be_replaced and not contains(ironmongery_part_no_list, trickle_vents) and not is_front_door',
  'NO TRICKLE VENTS! ADD QUOTE NOTE: No trickle vents included due to planning restrictions.',
  NULL,
  false,
  'empty list: trickle_vents'
);

-- Rule 101: Internal Bolection Moulding Front Door [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Internal Bolection Moulding Front Door',
  0,
  NULL,
  'item',
  'information',
  'is_bolection_moulding_around_panel_internally and is_front_door',
  'Bolection mouldings reduce the flat of muntins by 40mm. Take this into account with knockers & letter plates',
  NULL,
  false,
  'missing variable: is_bolection_moulding_around_panel_internally'
);

-- Rule 102: (unnamed) [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  '',
  0,
  NULL,
  'item',
  'information',
  'has_plantation_shutters and remove_and_refit_existing_sdg_or_panel',
  'ADD QUOTE NOTE: To remove and refit plantation shutters. Please note, while we will take every care, there is a small risk that the shutters may sustain unavoidable damage during removal or may no longer fit as before.',
  NULL,
  false,
  'missing variable: has_plantation_shutters, remove_and_refit_existing_sdg_or_panel'
);

-- Rule 103: Idigbo Warning [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Idigbo Warning',
  0,
  NULL,
  'item',
  'warning',
  'is_idigbo_frame or is_idigbo_sash',
  'SPEAK TO NATHAN BEFORE QUOTING THIS JOB',
  NULL,
  true,
  NULL
);

-- Rule 104: (unnamed) [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  '',
  0,
  NULL,
  'item',
  'information',
  'has_panelling or has_shutter_boxes and remove_and_refit_existing_sdg_or_panel',
  'ADD QUOTE NOTE: To remove, refit and redecorate existing surrounds. Please note, while we will take every care, there is a small risk that the surrounds may sustain unavoidable damage during removal or may no longer fit as before. If this happens we will liaise with you to determine the best way forward.',
  NULL,
  false,
  'missing variable: has_panelling, has_shutter_boxes, remove_and_refit_existing_sdg_or_panel'
);

-- Rule 105: External Bolection Moulding Front Door [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'External Bolection Moulding Front Door',
  1,
  NULL,
  'item',
  'information',
  'is_bolection_moulding_around_panel_externally and is_front_door',
  'Bolection mouldings reduce the flat of muntins by 40mm. Take this into account with knockers & letter plates',
  NULL,
  false,
  'missing variable: is_bolection_moulding_around_panel_externally'
);

-- Rule 106: Varnished vs finger joints [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Varnished vs finger joints',
  10,
  NULL,
  'item',
  'warning',
  'new_sash_qty > 0 and has_finger_jointed_material and is_varnished_or_stained',
  'Finger jointed material is not recommended on varnished or stained item',
  NULL,
  false,
  'missing variable: has_finger_jointed_material'
);

-- Rule 107: Fit to prepared opening [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Fit to prepared opening',
  10,
  NULL,
  'item',
  'information',
  'fit_to_prepared_opening',
  'ADD QUOTE NOTE: Please note, where the customer/contractor is preparing the opening, the customer must sign off on the final overall dimensions',
  NULL,
  true,
  NULL
);

-- Rule 108: Cill depth vs height [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Cill depth vs height',
  20,
  NULL,
  'item',
  'warning',
  'new_frame_qty > 0 and cill_height > 1 and cill_height < 40 and cill_depth > 150 and not is_sliding_door_set',
  'Deep cill require taller inner cill height',
  NULL,
  false,
  'product not offered'
);

-- Rule 109: Non-Standard Paint [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Non-Standard Paint',
  31,
  NULL,
  'item',
  'information',
  'nj_involved and not is_standard_finish_internally_and_externally',
  'For non-standard paint finishes, ensure the paint is specified as follows - Teknos Spray Finish BRAND COLOUR GLOSS/SATIN Colour Match',
  'For non-standard paint finishes, ensure the paint is specified as follows - Teknos Spray Finish BRAND COLOUR [GLOSS/SATIN] Colour Match',
  true,
  NULL
);

-- Rule 110: DSO with standard paint [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'DSO with standard paint',
  32,
  NULL,
  'item',
  'warning',
  'is_standard_finish_internally_and_externally and not nj_involved',
  'Draught sealing work with decoration should not be specified as Spray Finish. Change to Hand Finish',
  NULL,
  true,
  NULL
);

-- Rule 111: Cut Back Plaster [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Cut Back Plaster',
  40,
  NULL,
  'item',
  'warning',
  'cut_back_plaster',
  'The system allows 1.5 hours for cutting back plaster. If you think it needs more time, please add as a POA. Note that this is NOT to be used for cutting out a brick reveal where this has been blocked/bricked up.',
  NULL,
  true,
  NULL
);

-- Rule 112: Cut Out Brick Reveal [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Cut Out Brick Reveal',
  45,
  NULL,
  'item',
  'warning',
  'cut_out_brick_reveal',
  'The system allows 4 hours for cutting out a brick reveal. If you think it needs more time, please add as a POA. Note that this is NOT to be used for cutting/trimming back plaster. Please also add the following quote note: In order to fit this window and to ensure it is correctly proportioned, we will need to cut away brickwork. This will create dust. During installation, we strongly recommend you remove or cover all personal belongings in the room.',
  NULL,
  true,
  NULL
);

-- Rule 113: Secondary Glazing Decoration [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Secondary Glazing Decoration',
  200,
  NULL,
  'item',
  'information',
  '( remove_and_refit_existing_sdg_or_panel or remove_and_dispose_existing_sdg_or_panel ) and new_frame_qty == 0 and is_decoration_included',
  'ADD QUOTE NOTE: Please note that we have allowed for light rubbing down of the existing box frame only. If removal of secondary glazing/shutter/grille causes extensive damage and a full strip back is required an additional charge may be necessary.',
  NULL,
  false,
  'missing variable: remove_and_refit_existing_sdg_or_panel, remove_and_dispose_existing_sdg_or_panel'
);

-- Rule 114: Decoration Text [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Decoration Text',
  200,
  NULL,
  'item',
  'information',
  'is_decoration_included',
  'Add quote note: To include for repainting the existing box frames. Lightly rub down, fill where necessary and apply one coat of acrylic primer undercoat and one top coat.',
  NULL,
  true,
  NULL
);

-- Rule 115: Encapsulated Leaded Lights [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Encapsulated Leaded Lights',
  300,
  NULL,
  'item',
  'warning',
  'encapsulated_leaded_light_qty >= 1',
  'No pricing has been allowed for encapsulated leaded lights. This must be worked out and specified by you.',
  NULL,
  true,
  NULL
);

-- Rule 116: Bay Type [Recommendation]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Recommendation'),
  'Bay Type',
  300,
  NULL,
  'item',
  'warning',
  'is_bay_joined_internally or is_bay_with_full_timber_mullion',
  'If this customer proceeds, Kera should follow SOP 1.16',
  NULL,
  false,
  'missing variable: is_bay_joined_internally, is_bay_with_full_timber_mullion'
);

-- Rule 117: Banham [Ironmongery]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Ironmongery'),
  'Banham',
  10,
  'ironmongery_part',
  'item',
  'warning',
  'part_no == im300120',
  'When using Banham locks, stiles and top rails must be increased to 118mm',
  NULL,
  false,
  'part type not built yet: ironmongery_part'
);

-- Rule 118: Ironmongery Quantity [Ironmongery]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Ironmongery'),
  'Ironmongery Quantity',
  11,
  NULL,
  'item',
  'information',
  'sliding_pair_qty >= 2',
  'Make sure the correct amount of ironmongery/surround/beading is included',
  NULL,
  true,
  NULL
);

-- Rule 119: Ironmongery Quantity [Ironmongery]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Ironmongery'),
  'Ironmongery Quantity',
  11,
  NULL,
  'item',
  'information',
  'frame_qty >= 2',
  'Make sure the correct amount of ironmongery/surround/beading is included',
  NULL,
  true,
  NULL
);

-- Rule 120: Over 24kg Casement Sash [Friction Hinges]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Friction Hinges'),
  'Over 24kg Casement Sash',
  10,
  'casement_sash',
  'item',
  'error',
  'weight_in_kg > 45 and is_opening and is_side_hung',
  'We can! do side hung opening casement sashes over 45kg',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 121: French Casement Min Size [Casement Espags]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Casement Espags'),
  'French Casement Min Size',
  0,
  NULL,
  'item',
  'warning',
  'new_french_casement_pair_qty >= 1 and overall_frame_width < 0.86',
  'Minimum frame width for French casement windows is 860mm because there needs to be two 13 inch friction stays. Either change this so it is not a French casement or untick MPLS, remove friction hinges and add butt hinges.',
  NULL,
  false,
  'missing variable: new_french_casement_pair_qty'
);

-- Rule 122: Not MPLS [Casement Espags]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Casement Espags'),
  'Not MPLS',
  80,
  'casement_sash',
  'item',
  'warning',
  'not is_heritage_range and not is_casement_mpls and is_opening',
  'This window is not drawn up with a multipoint locking system. If it should have one, go to Finish & Ironmongery and tick MPLS for Casement',
  NULL,
  false,
  'product not offered'
);

-- Rule 123: Too Long [Casement Espags]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Casement Espags'),
  'Too Long',
  90,
  'casement_sash',
  'item',
  'error',
  'is_opening and is_top_hung and gross_sash_width_in_mm > 2798',
  'A top hung casement sash can! be wider than 2798mm',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 124: Short Casement Espag [Casement Espags]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Casement Espags'),
  'Short Casement Espag',
  100,
  'casement_sash',
  'item',
  'error',
  'is_top_hung and gross_sash_width_in_mm < 306 and is_casement_mpls',
  'The minimum length to fit a multipoint lock on a casement is 306mm. Please untick Casement MPLS and click Default Ironmongery',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 125: Short Casement Espag [Casement Espags]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Casement Espags'),
  'Short Casement Espag',
  110,
  'casement_sash',
  'item',
  'error',
  'is_side_hung and gross_sash_height_in_mm < 306 and is_casement_mpls',
  'The minimum length to fit a multipoint lock on a casement is 306mm. Please untick Casement MPLS and click Default Ironmongery',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 126: Overweight sash [Health & Safety]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Health & Safety'),
  'Overweight sash',
  10,
  'sliding_sash',
  'item',
  'warning',
  'weight_in_kg > 28.5',
  '!! Please note that this item must be installed by two people due to the weightt of the sash and for H&S reasons. Surveyors - you can disregard this, as the price has already been adjusted. Charlie - please add this as an IOFN. James - please make sure this item is done by two people.',
  NULL,
  true,
  NULL
);

-- Rule 127: Overweight sash [Health & Safety]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Health & Safety'),
  'Overweight sash',
  30,
  'door_leaf',
  'item',
  'warning',
  'weight_in_kg > 25',
  '!! Please note that this item must be installed by two people due to the weightt of the sash and for H&S reasons. Surveyors - you can disregard this, as the price has already been adjusted. Charlie - please add this as an IOFN. James - please make sure this item is done by two people.',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 128: Overweight sash [Health & Safety]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Health & Safety'),
  'Overweight sash',
  1000,
  'casement_sash',
  'item',
  'warning',
  'weight_in_kg > 25',
  '!! Please note that this item must be installed by two people due to the weightt of the sash and for H&S reasons. Surveyors - you can disregard this, as the price has already been adjusted. Charlie - please add this as an IOFN. James - please make sure this item is done by two people.',
  NULL,
  false,
  'part type not built yet: casement_sash'
);

-- Rule 129: Panels [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Panels',
  0,
  'panel',
  'item',
  'warning',
  'not internal_panel_type == external_panel_type',
  'PLEASE NOTE WE ONLY MANUFACTURE PANELS THE SAME INTERNAL AND EXTERNAL. DO NOT QUOTE DIFFERENT PANELS',
  NULL,
  false,
  'part type not built yet: panel'
);

-- Rule 130: Stain with T&G Panel [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Stain with T&G Panel',
  0,
  'panel',
  'item',
  'error',
  'is_varnished_or_stained and is_tongue_and_groove_panel_externally or is_varnished_or_stained and is_tongue_and_groove_panel_internally',
  'T&G PANELS ARE NOT POSSIBLE WITH STAINED JOINERY',
  NULL,
  false,
  'part type not built yet: panel'
);

-- Rule 131: Midrail & Transom Info [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Midrail & Transom Info',
  0,
  NULL,
  'item',
  'warning',
  'is_open_in_doors_range or is_single_and_french_doors_range and sash_transom_qty >= 1',
  'If suitable, please make midrail 170mm.',
  NULL,
  false,
  'missing variable: is_open_in_doors_range, is_single_and_french_doors_range, sash_transom_qty'
);

-- Rule 132: Midrail & Transom Info [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Midrail & Transom Info',
  0,
  NULL,
  'item',
  'warning',
  'is_open_in_doors_range or is_single_and_french_doors_range and sash_mullion_qty >= 1',
  'If suitable, please make door mullions 120mm.',
  NULL,
  false,
  'missing variable: is_open_in_doors_range, is_single_and_french_doors_range, sash_mullion_qty'
);

-- Rule 133: MPLS Door [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'MPLS Door',
  10,
  'door_leaf',
  'item',
  'error',
  'is_door_mpls and gross_sash_height_in_mm > 2923',
  'DOOR CANNOT BE MULTIPOINT IF OVER 2923MM IN DOOR HEIGHT',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 134: Non-MPLS with Bolection [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Non-MPLS with Bolection',
  55,
  NULL,
  'item',
  'error',
  'is_bolection_moulding_around_panel_externally and not is_door_mpls',
  'DOORS WITH BOLECTION MOULDINGS MUST HAVE A MULTIPOINT LOCKING SYSTEM',
  NULL,
  false,
  'missing variable: is_bolection_moulding_around_panel_externally, is_door_mpls'
);

-- Rule 135: Non-MPLS with Bolection [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Non-MPLS with Bolection',
  60,
  NULL,
  'item',
  'error',
  'is_bolection_moulding_around_panel_internally and not is_door_mpls',
  'DOORS WITH BOLECTION MOULDINGS MUST HAVE A MULTIPOINT LOCKING SYSTEM',
  NULL,
  false,
  'missing variable: is_bolection_moulding_around_panel_internally, is_door_mpls'
);

-- Rule 136: Small Sliding Doors [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Small Sliding Doors',
  105,
  NULL,
  'item',
  'error',
  'is_sliding_door_set and overall_sash_width_for_widest_farame <= 1.379',
  'MINIMUM COMBINED DOOR WIDTH FOR SLIDING DOORS IS 1380MM',
  NULL,
  false,
  'product not offered'
);

-- Rule 137: Too Wide Sliding Doors [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Too Wide Sliding Doors',
  110,
  NULL,
  'item',
  'error',
  'is_sliding_door_set and overall_sash_width_for_widest_farame > 4.402',
  'MAXIMUM COMBINED DOOR LEAF WIDTH FOR SLIDING DOORS IS 4402MM. SPEAK TO NATHAN BEFORE PROCEEDING.',
  NULL,
  false,
  'product not offered'
);

-- Rule 138: SHORT Sliding Doors [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'SHORT Sliding Doors',
  115,
  NULL,
  'item',
  'error',
  'is_sliding_door_set and overall_sash_height < 0.745',
  'DOOR HEIGHT IS TOO SMALL FOR SLIDING DOORS. MUST BE 745MM MINIMUM',
  NULL,
  false,
  'product not offered'
);

-- Rule 139: TALL Sliding Doors [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'TALL Sliding Doors',
  120,
  NULL,
  'item',
  'error',
  'is_sliding_door_set and overall_sash_height > 3.3',
  'DOOR HEIGHT IS TOO TALL FOR SLIDING DOORS. MAXIMUM IS 3300MM',
  NULL,
  false,
  'product not offered'
);

-- Rule 140: Door height below UK standard [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Door height below UK standard',
  125,
  'door_leaf',
  'item',
  'warning',
  'profiled_frame_interior_height_in_mm < 1980',
  'Door is less than 1980mm tall (UK Standard) - profiled_frame_interior_height_in_mm',
  'In progress',
  false,
  'part type not built yet: door_leaf'
);

-- Rule 141: Door height below UK standard [Doors]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Doors'),
  'Door height below UK standard',
  125,
  'door_leaf',
  'item',
  'warning',
  'gross_sash_height_in_mm < 1980',
  'Door is less than 1980mm tall (UK Standard)',
  NULL,
  false,
  'part type not built yet: door_leaf'
);

-- Rule 142: Trickle Vent Position [Factory]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Factory'),
  'Trickle Vent Position',
  0,
  NULL,
  'item',
  'information',
  'has_allocated_trickle_vent and ( is_casement_window or is_casement_window_bay or is_door )',
  'Trickle vent will be 15m below the top of the frame. Ensure there is enough clearance internally and externally for the vents',
  NULL,
  false,
  'missing variable: has_allocated_trickle_vent'
);

-- Rule 143: HCJ [Factory]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Factory'),
  'HCJ',
  1,
  NULL,
  'item',
  'information',
  'is_survey_drawing and (is_casement_window or bi_fold_door_leaf_qty > 0 or (door_leaf_qty > 0 and sliding_sash_qty > 0 and frame_qty == 1))',
  'LTW',
  NULL,
  false,
  'missing variable: bi_fold_door_leaf_qty'
);

-- Rule 144: LTW [Factory]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Factory'),
  'LTW',
  2,
  NULL,
  'item',
  'information',
  'is_survey_drawing and bi_fold_door_leaf_qty == 0 and door_leaf_qty > 0 and sliding_sash_qty == 0',
  'LTW',
  NULL,
  false,
  'missing variable: bi_fold_door_leaf_qty'
);

-- Rule 145: NFJ [Factory]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Factory'),
  'NFJ',
  3,
  NULL,
  'item',
  'information',
  'is_survey_drawing and sliding_sash_qty > 0 and is_complete_new and sash_with_curved_head_qty > 0 and frame_with_curved_inner_head_qty > 0 and is_single_glazed and is_individual_panes and gb_width !=22',
  'NFJ',
  NULL,
  false,
  'missing variable: sash_with_curved_head_qty, frame_with_curved_inner_head_qty'
);

-- Rule 146: NFJ/PSJ [Factory]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Factory'),
  'NFJ/PSJ',
  4,
  NULL,
  'item',
  'information',
  'is_survey_drawing and sliding_sash_qty > 0 and is_complete_new and sash_with_curved_head_qty == 0 and frame_with_curved_inner_head_qty == 0 and not is_single_glazed and not is_individual_panes',
  'NFJ/PSJ',
  NULL,
  false,
  'missing variable: sash_with_curved_head_qty, frame_with_curved_inner_head_qty'
);

-- Rule 147: NFJ [Factory]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Factory'),
  'NFJ',
  5,
  NULL,
  'item',
  'information',
  'is_survey_drawing and sliding_sash_qty > 0 and not is_complete_new and sash_with_curved_head_qty > 0 and is_single_glazed and is_individual_panes and (gb_width !=22 or contains(sash_thickness, allowed_sash_thickess))',
  'NFJ',
  NULL,
  false,
  'missing variable: sash_with_curved_head_qty'
);

-- Rule 148: Surrounds not allowed [To Be Checked]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'To Be Checked'),
  'Surrounds not allowed',
  1,
  NULL,
  'item',
  'error',
  'is_installation_level_test_1 and (has_architrave or has_lining or has_deep_window_board)',
  'Please remove any surrounds or adjust installation level. X Installation Level does not include (architraves/linings/window boards)',
  'Wait for Install level to be confirmed.',
  false,
  'missing variable: is_installation_level_test_1, has_architrave, has_lining, has_deep_window_board'
);

-- Rule 149: Heritage [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Heritage',
  1,
  NULL,
  'item',
  'information',
  'is_heritage_range',
  'HCJ',
  NULL,
  false,
  'product not offered'
);

-- Rule 150: No Argon Gas [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'No Argon Gas',
  5,
  'glass_unit',
  'item',
  'error',
  'is_heritage_range and to_be_replaced and is_double_glazed and not is_filled_with_krypton',
  'Argon gas not permitted in Heritage range',
  NULL,
  false,
  'product not offered'
);

-- Rule 151: Force individual panes [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Force individual panes',
  10,
  NULL,
  'item',
  'error',
  'is_heritage_range and is_double_glazed and gb_to_be_replaced_qty >= 1 and not is_individual_panes',
  'Heritage double glazing must be individual panes',
  NULL,
  false,
  'product not offered'
);

-- Rule 152: Heritage Spacer Dim [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Heritage Spacer Dim',
  15,
  'glass_unit',
  'item',
  'error',
  'is_heritage_range and is_double_glazed and (spacer_dim !=4 and spacer_dim !=6)',
  'Heritage double glazing must have 4mm or 6mm spacer',
  NULL,
  false,
  'product not offered'
);

-- Rule 153: Single Glazing max 7mm [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Single Glazing max 7mm',
  20,
  'glass_unit',
  'item',
  'error',
  'is_heritage_range and is_single_glazed and single_pane_thickness > 7',
  'Single glazing can be 7mm max',
  NULL,
  false,
  'product not offered'
);

-- Rule 154: Prevent DocL [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Prevent DocL',
  25,
  NULL,
  'item',
  'error',
  'is_heritage_range and is_docl',
  'Heritage range can! be DocL',
  NULL,
  false,
  'product not offered'
);

-- Rule 155: Non-Heritage Spacer Dim [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Non-Heritage Spacer Dim',
  30,
  'glass_unit',
  'item',
  'warning',
  'not is_heritage_range and is_double_glazed and spacer_dim == 4',
  'Non-heritage items can! have 4mm spacer',
  NULL,
  false,
  'product not offered'
);

-- Rule 156: Krypton not permitted for non-heritage [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Krypton not permitted for non-heritage',
  35,
  'glass_unit',
  'item',
  'warning',
  'not is_heritage_range and is_filled_with_krypton',
  'Non-heritage range items can! have Krypton gas',
  NULL,
  false,
  'product not offered'
);

-- Rule 157: Minimum GB width for non-heritage [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Minimum GB width for non-heritage',
  40,
  NULL,
  'item',
  'warning',
  'not is_individual_panes and gb_qty >= 1 and gb_width < 22',
  'Non-heritage items can! have glazing bars less than 22mm width',
  NULL,
  false,
  'product not offered'
);

-- Rule 158: Minimum GB width for heritage [Heritage]
INSERT INTO public.validation_rules (group_id, name, sort_order, loop_target, level, severity, condition, message, comment, is_active, blocked_reason)
VALUES (
  (SELECT id FROM public.validation_groups WHERE name = 'Heritage'),
  'Minimum GB width for heritage',
  41,
  NULL,
  'item',
  'warning',
  'is_individual_panes and gb_qty >= 1 and gb_width < 20',
  'Heritage items can! have glazing bars less than 20mm width',
  NULL,
  false,
  'product not offered'
);

-- ══════════════════════════════════════════════════════════════════════════════
-- ROLLBACK
-- ══════════════════════════════════════════════════════════════════════════════
-- DELETE FROM public.validation_rules
--   WHERE group_id IN (SELECT id FROM public.validation_groups);
--
-- DELETE FROM public.validation_lists WHERE name IN (
--   'landvac_fineo', '6_8_acoustic', 'trickle_vents', 'timber'
-- );
