-- DO NOT RUN DIRECTLY — paste into Supabase SQL editor.
-- =============================================================================
-- step-g3-default-ironmongery.sql
--
-- Step G3: Default Ironmongery
--   1. Extend part_allocation_rules with rule_family, product_short_name,
--      finish_code columns and a CHECK constraint.
--   2. Add ironmongeryFinish field definition to default_field_definitions.
--   3. Seed 91 default_ironmongery rules into part_allocation_rules.
--
-- Safe to re-run: all DDL uses IF NOT EXISTS / DO $$ guards; all DML uses
-- WHERE NOT EXISTS guards so duplicate rows are never inserted.
-- Generated by scripts/build-step-g-sql.mjs — do not edit manually
-- =============================================================================

BEGIN;

-- =============================================================================
-- STEP 1: ALTER part_allocation_rules
-- =============================================================================

ALTER TABLE part_allocation_rules
  ADD COLUMN IF NOT EXISTS rule_family         text NOT NULL DEFAULT 'part_allocator',
  ADD COLUMN IF NOT EXISTS product_short_name  text,
  ADD COLUMN IF NOT EXISTS finish_code         text;

-- CHECK constraint: only two families allowed
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'part_allocation_rules_rule_family_check'
  ) THEN
    ALTER TABLE part_allocation_rules
      ADD CONSTRAINT part_allocation_rules_rule_family_check
      CHECK (rule_family IN ('part_allocator', 'default_ironmongery'));
  END IF;
END $$;

-- Ensure all pre-existing rows are explicitly stamped as 'part_allocator'
UPDATE part_allocation_rules
   SET rule_family = 'part_allocator'
 WHERE rule_family IS NULL OR rule_family = 'part_allocator';


-- =============================================================================
-- STEP 2: ironmongeryFinish field definition
-- =============================================================================

INSERT INTO default_field_definitions (
  part_type,
  field_key,
  property_name,
  label,
  data_type,
  is_required,
  reference_category,
  sort_order,
  is_active
) VALUES (
  'paintAndIronmongeryPart',
  'paintAndIronmongeryPart.ironmongeryFinish',
  'ironmongeryFinish',
  'Ironmongery Finish',
  'reference',
  false,
  'ironmongery_finish',
  1000,
  true
) ON CONFLICT (field_key) DO UPDATE SET
  reference_category = EXCLUDED.reference_category,
  label              = EXCLUDED.label,
  data_type          = EXCLUDED.data_type;


-- =============================================================================
-- STEP 3: Seed 91 default ironmongery rules
-- =============================================================================

-- ---------------------------------------------------------------------------
-- GROUP: sash_windows
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 0, 'sash_windows', 'sliding_sash', 'Box Frame',
  'is_complete_new and is_cord_hung',
  '0.5', NULL, NULL, true,
  'default_ironmongery', 'z-claw_fastener_kit_wpulleys', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 0
     AND product_short_name = 'z-claw_fastener_kit_wpulleys'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 5, 'sash_windows', 'sliding_sash', 'Box Frame',
  'is_complete_new and is_spiral_hung',
  '0.5', NULL, NULL, true,
  'default_ironmongery', 'z-claw_fastener_kit_wopulleys', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 5
     AND product_short_name = 'z-claw_fastener_kit_wopulleys'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'sash_windows', NULL, 'Pair of Sashes',
  'is_sw and nj_involved and not frame_to_be_replaced',
  'new_opening_sliding_sash_qty / 2', NULL, NULL, true,
  'default_ironmongery', 'z-claw_fastener_kit_wopulleys', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 10
     AND product_short_name = 'z-claw_fastener_kit_wopulleys'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 15, 'sash_windows', NULL, 'DSO',
  'needs_draughtsealing and not nj_involved',
  'sliding_pair_with_opening_sash_qty', NULL, NULL, true,
  'default_ironmongery', 'z-brighton_fastener_kit_wpulleys', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 15
     AND product_short_name = 'z-brighton_fastener_kit_wpulleys'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 20, 'sash_windows', NULL, 'Yorkshire',
  'is_yorkshire_sash_window',
  '1', NULL, NULL, false,
  'default_ironmongery', 'yorkshire_sash_kit', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 20
     AND product_short_name = 'yorkshire_sash_kit'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 50, 'sash_windows', NULL, 'Trickle Vent',
  'frame_to_be_replaced and not is_front_door and not is_heritage_range',
  '1', NULL, NULL, true,
  'default_ironmongery', 'trickle_vent_xr16', 'Wht'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 50
     AND product_short_name = 'trickle_vent_xr16'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 52, 'sash_windows', NULL, 'Trickle Vent',
  'frame_to_be_replaced and not is_front_door and not is_heritage_range and not is_sw',
  '1', NULL, NULL, true,
  'default_ironmongery', 'trickle', 'Wht'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 52
     AND product_short_name = 'trickle'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 55, 'sash_windows', 'sliding_sash', 'Chains',
  'is_chain_hung and to_be_replaced',
  '1', NULL, NULL, true,
  'default_ironmongery', 'linked_sash_chain', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'sash_windows' AND sort_order = 55
     AND product_short_name = 'linked_sash_chain'
);

-- ---------------------------------------------------------------------------
-- GROUP: front_doors
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 0, 'front_doors', NULL, NULL,
  'new_stable_door_pair_qty == 1',
  '2', NULL, NULL, true,
  'default_ironmongery', 'double_euro_cylinder', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 0
     AND product_short_name = 'double_euro_cylinder'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 0, 'front_doors', NULL, NULL,
  'new_stable_door_pair_qty == 1',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_lyndon_door_espag_set', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 0
     AND product_short_name = 'hardwick_lyndon_door_espag_set'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 0, 'front_doors', NULL, NULL,
  'new_stable_door_pair_qty == 1',
  '1', NULL, NULL, true,
  'default_ironmongery', 'winkhaus_interlocking_stable_door_multipoint_lock', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 0
     AND product_short_name = 'winkhaus_interlocking_stable_door_multipoint_lock'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'front_doors', NULL, 'Nightlatch',
  'is_front_door and nj_involved',
  '1', NULL, NULL, false,
  'default_ironmongery', 'era_nightlatch', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 10
     AND product_short_name = 'era_nightlatch'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 15, 'front_doors', NULL, 'Deadlock',
  'is_front_door and nj_involved',
  '1', NULL, NULL, false,
  'default_ironmongery', 'era_deadlock', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 15
     AND product_short_name = 'era_deadlock'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 20, 'front_doors', NULL, 'Letterplate',
  'is_front_door and nj_involved',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_classic_sleeved_letterbox', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 20
     AND product_short_name = 'hardwick_classic_sleeved_letterbox'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 27, 'front_doors', 'door_leaf', 'Front Door Euro Cylinder Pull',
  'is_front_door and is_door_mpls and not is_master_leaf_in_french_pair',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_classic_euro_pull_set_back_to_back', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 27
     AND product_short_name = 'hardwick_classic_euro_pull_set_back_to_back'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 30, 'front_doors', 'door_leaf', 'Front Door Open In Left Hand Hung',
  'is_front_door and is_opening_in and is_left_hand_hung_viewed_internally and is_door_mpls and not is_master_leaf_in_french_pair',
  '1', NULL, NULL, true,
  'default_ironmongery', 'av3_heritage_locking_system_lh', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 30
     AND product_short_name = 'av3_heritage_locking_system_lh'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 35, 'front_doors', 'door_leaf', 'Front Door Open In Right Hand Hung',
  'is_front_door and is_opening_in and is_right_hand_hung_viewed_internally and is_door_mpls and not is_master_leaf_in_french_pair',
  '1', NULL, NULL, true,
  'default_ironmongery', 'av3_heritage_locking_system_rh', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 35
     AND product_short_name = 'av3_heritage_locking_system_rh'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 40, 'front_doors', 'door_leaf', 'Front Door Open Out Left Hand Hung',
  'is_front_door and is_opening_out and is_left_hand_hung_viewed_internally and is_door_mpls and not is_master_leaf_in_french_pair',
  '1', NULL, NULL, true,
  'default_ironmongery', 'av3_heritage_locking_system_rh', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 40
     AND product_short_name = 'av3_heritage_locking_system_rh'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 45, 'front_doors', 'door_leaf', 'Front Door Open Out Right Hand Hung',
  'is_front_door and is_opening_out and is_right_hand_hung_viewed_internally and is_door_mpls and not is_master_leaf_in_french_pair',
  '1', NULL, NULL, true,
  'default_ironmongery', 'av3_heritage_locking_system_lh', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'front_doors' AND sort_order = 45
     AND product_short_name = 'av3_heritage_locking_system_lh'
);

-- ---------------------------------------------------------------------------
-- GROUP: bifolding_doors
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'bifolding_doors', NULL, '2 Left',
  'is_bi_fold_door_set and door_leaf_qty_folding_left == 2',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_pivot_set', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 10
     AND product_short_name = 'centor_pivot_set'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 11, 'bifolding_doors', NULL, '2 Left',
  'is_bi_fold_door_set and door_leaf_qty_folding_left == 2',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_wall_pivot_set', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 11
     AND product_short_name = 'centor_wall_pivot_set'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 12, 'bifolding_doors', NULL, '2 Left',
  'is_bi_fold_door_set and door_leaf_qty_folding_left == 2',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_lh_carrier', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 12
     AND product_short_name = 'centor_lh_carrier'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 15, 'bifolding_doors', NULL, '2 Left',
  'is_bi_fold_door_set and door_leaf_qty_folding_left == 2',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_wall_pivot_set', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 15
     AND product_short_name = 'centor_wall_pivot_set'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 100, 'bifolding_doors', NULL, '2400mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 2400',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_2440', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 100
     AND product_short_name = 'centor_2440'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 101, 'bifolding_doors', NULL, '2400mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 2400',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_2440', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 101
     AND product_short_name = 'centor_2440'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 105, 'bifolding_doors', NULL, '3000mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 3000',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_3640t', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 105
     AND product_short_name = 'centor_3640t'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 105, 'bifolding_doors', NULL, '3000mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 3000',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_3640', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 105
     AND product_short_name = 'centor_3640'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 110, 'bifolding_doors', NULL, '4000mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 4000',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_4240', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 110
     AND product_short_name = 'centor_4240'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 111, 'bifolding_doors', NULL, '4000mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 4000',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_4240', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 111
     AND product_short_name = 'centor_4240'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 115, 'bifolding_doors', NULL, '5700mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 5700',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_5740', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 115
     AND product_short_name = 'centor_5740'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 116, 'bifolding_doors', NULL, '5700mm Top Track',
  'is_bi_fold_door_set and overall_frame_width_in_mm <= 5700',
  '1', NULL, NULL, false,
  'default_ironmongery', 'centor_5740t', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'bifolding_doors' AND sort_order = 116
     AND product_short_name = 'centor_5740t'
);

-- ---------------------------------------------------------------------------
-- GROUP: friction_hinges
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'friction_hinges', 'casement_sash', 'Up to 600mm',
  'is_opening and (gross_sash_width_in_mm <= 600) and (weight_in_kg <= 22) and (gross_sash_height_in_mm <= 1300) and is_side_hung and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_friction_hinge_-_side_hung_310mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 10
     AND product_short_name = 'defender_friction_hinge_-_side_hung_310mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 11, 'friction_hinges', 'casement_sash', 'Up to 600mm',
  'is_opening and is_side_hung and weight_in_kg > 22 and gross_sash_width_in_mm <= 600 or is_opening and is_side_hung and weight_in_kg > 22 and gross_sash_height_in_mm >= 1300 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 11
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 12, 'friction_hinges', 'casement_sash', 'Up to 600mm [weight_in_kg]',
  'is_opening and is_side_hung and gross_sash_height_in_mm >= 1300 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 12
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 15, 'friction_hinges', 'casement_sash', 'Up to 700mm',
  'is_opening and (gross_sash_width_in_mm <= 700) and gross_sash_width_in_mm > 600 and (weight_in_kg <= 24) and (gross_sash_height_in_mm <= 1300) and is_side_hung and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_friction_hinge_-_side_hung_412mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 15
     AND product_short_name = 'defender_friction_hinge_-_side_hung_412mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 16, 'friction_hinges', 'casement_sash', 'Up to 700mm',
  'is_opening and is_side_hung and weight_in_kg > 24 and weight_in_kg < 45 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 16
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 20, 'friction_hinges', 'casement_sash', '8 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 350 and weight_in_kg <= 12 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_209mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 20
     AND product_short_name = 'defender_209mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 21, 'friction_hinges', 'casement_sash', '8 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 350 and weight_in_kg > 12 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 21
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 22, 'friction_hinges', 'casement_sash', 'Over 700mm casement hinges',
  'is_side_hung and gross_sash_width_in_mm > 700 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 22
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 25, 'friction_hinges', 'casement_sash', '12 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 550 and gross_sash_height_in_mm > 350 and weight_in_kg <= 20 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_310mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 25
     AND product_short_name = 'defender_310mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 26, 'friction_hinges', 'casement_sash', '12 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 550 and gross_sash_height_in_mm > 350 and weight_in_kg > 20 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 26
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 30, 'friction_hinges', 'casement_sash', '16 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 750 and gross_sash_height_in_mm > 550 and weight_in_kg <= 21 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_310mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 30
     AND product_short_name = 'defender_310mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 31, 'friction_hinges', 'casement_sash', '16 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 750 and gross_sash_height_in_mm > 550 and weight_in_kg > 21 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 31
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 35, 'friction_hinges', 'casement_sash', '20 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 1000 and gross_sash_height_in_mm > 750 and weight_in_kg <= 26 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_412mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 35
     AND product_short_name = 'defender_412mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 36, 'friction_hinges', 'casement_sash', '20 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 1000 and gross_sash_height_in_mm > 750 and weight_in_kg > 26 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 36
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 40, 'friction_hinges', 'casement_sash', '24 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 1200 and gross_sash_height_in_mm > 1000 and weight_in_kg <= 40 and not is_heritage_range and not is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'defender_615mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 40
     AND product_short_name = 'defender_615mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 41, 'friction_hinges', 'casement_sash', '24 inch top hung',
  'is_top_hung and gross_sash_height_in_mm <= 1200 and gross_sash_height_in_mm > 1000 and weight_in_kg > 40 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 41
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 45, 'friction_hinges', 'casement_sash', 'Top Hung Over 1200mm',
  'is_opening and is_top_hung and gross_sash_height_in_mm > 1200 and not is_heritage_range and not is_french_casement_sash',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 45
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 50, 'friction_hinges', 'casement_sash', 'French Casement',
  'is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 50
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 55, 'friction_hinges', 'casement_sash', 'French Casement',
  'is_french_casement_sash',
  '1', NULL, NULL, true,
  'default_ironmongery', 'timbersuite_locking_stay', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'friction_hinges' AND sort_order = 55
     AND product_short_name = 'timbersuite_locking_stay'
);

-- ---------------------------------------------------------------------------
-- GROUP: mpls_casement
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 5, 'mpls_casement', 'casement_sash', 'Casement Handle',
  'is_opening and is_casement_mpls and is_left_hand_hung_viewed_internally',
  '1', NULL, NULL, true,
  'default_ironmongery', 'connoisseur_handle_lh', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 5
     AND product_short_name = 'connoisseur_handle_lh'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 6, 'mpls_casement', 'casement_sash', 'Casement Handle',
  'is_opening and is_casement_mpls and is_right_hand_hung_viewed_internally',
  '1', NULL, NULL, true,
  'default_ironmongery', 'connoisseur_handle_rh', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 6
     AND product_short_name = 'connoisseur_handle_rh'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 7, 'mpls_casement', 'casement_sash', 'Casement Handle',
  'is_opening and is_casement_mpls and is_top_hung',
  '1', NULL, NULL, true,
  'default_ironmongery', 'connoisseur_handle_lh', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 7
     AND product_short_name = 'connoisseur_handle_lh'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'mpls_casement', 'casement_sash', 'Espag Gearbox',
  'is_opening and is_casement_mpls',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_gear_box', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 10
     AND product_short_name = 'kenrick_extension_gear_box'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 15, 'mpls_casement', 'casement_sash', '306-442mm Extensions',
  'is_opening and is_casement_mpls and is_top_hung and gross_sash_width_in_mm <= 442 and gross_sash_width_in_mm >= 306',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 15
     AND product_short_name = 'kenrick_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 20, 'mpls_casement', 'casement_sash', '443-502mm Extensions',
  'is_opening and is_casement_mpls and is_top_hung and gross_sash_width_in_mm <= 502 and gross_sash_width_in_mm >= 443',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_370mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 20
     AND product_short_name = 'kenrick_extension_370mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 25, 'mpls_casement', 'casement_sash', '503-698mm Extensions',
  'is_opening and is_casement_mpls and is_top_hung and gross_sash_width_in_mm <= 698 and gross_sash_width_in_mm >= 503',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_490mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 25
     AND product_short_name = 'kenrick_extension_490mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 30, 'mpls_casement', 'casement_sash', '699-956mm Extensions',
  'is_opening and is_casement_mpls and is_top_hung and gross_sash_width_in_mm <= 956 and gross_sash_width_in_mm >= 699',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_690mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 30
     AND product_short_name = 'kenrick_extension_690mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 35, 'mpls_casement', 'casement_sash', '957-1212mm Extensions',
  'is_opening and is_casement_mpls and is_top_hung and gross_sash_width_in_mm <= 1212 and gross_sash_width_in_mm >= 957',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_950mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 35
     AND product_short_name = 'kenrick_extension_950mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 40, 'mpls_casement', 'casement_sash', '1213-1476 mm Extensions',
  'is_opening and is_casement_mpls and is_top_hung and gross_sash_width_in_mm <= 1476 and gross_sash_width_in_mm >= 1213',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_1210mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 40
     AND product_short_name = 'kenrick_extension_1210mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 45, 'mpls_casement', 'casement_sash', '1504mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 1476 and gross_sash_width_in_mm <= 1504',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 45
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 46, 'mpls_casement', 'casement_sash', '1504mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 1476 and gross_sash_width_in_mm <= 1504',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_950mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 46
     AND product_short_name = 'kenrick_extension_950mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 50, 'mpls_casement', 'casement_sash', '1505mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 1504 and gross_sash_width_in_mm <= 1770',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_490mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 50
     AND product_short_name = 'kenrick_extension_490mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 51, 'mpls_casement', 'casement_sash', '1505mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 1504 and gross_sash_width_in_mm <= 1770',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 51
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 55, 'mpls_casement', 'casement_sash', '1771mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 1771 and gross_sash_width_in_mm <= 2286',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_690mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 55
     AND product_short_name = 'kenrick_extension_690mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 56, 'mpls_casement', 'casement_sash', '1771mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 1771 and gross_sash_width_in_mm <= 2286',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 56
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 60, 'mpls_casement', 'casement_sash', '2798mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 2286 and gross_sash_width_in_mm <= 2798',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_1210mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 60
     AND product_short_name = 'kenrick_extension_1210mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 61, 'mpls_casement', 'casement_sash', '2798mm Extensions',
  'is_opening and is_top_hung and is_casement_mpls and gross_sash_width_in_mm > 2286 and gross_sash_width_in_mm <= 2798',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 61
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 100, 'mpls_casement', 'casement_sash', 'Side Hung 306-442mm Extensions',
  'is_opening and is_casement_mpls and is_side_hung and gross_sash_height_in_mm <= 442 and gross_sash_height_in_mm >= 306',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 100
     AND product_short_name = 'kenrick_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 105, 'mpls_casement', 'casement_sash', 'Side Hung 443-502mm Extensions',
  'is_opening and is_casement_mpls and is_side_hung and gross_sash_height_in_mm <= 502 and gross_sash_height_in_mm >= 443',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_370mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 105
     AND product_short_name = 'kenrick_extension_370mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 110, 'mpls_casement', 'casement_sash', 'Side Hung 503-698mm Extensions',
  'is_opening and is_casement_mpls and is_side_hung and gross_sash_height_in_mm <= 698 and gross_sash_height_in_mm >= 503',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_490mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 110
     AND product_short_name = 'kenrick_extension_490mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 120, 'mpls_casement', 'casement_sash', 'Side Hung 699-956mm Extensions',
  'is_opening and is_casement_mpls and is_side_hung and gross_sash_height_in_mm <= 956 and gross_sash_height_in_mm >= 699',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_690mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 120
     AND product_short_name = 'kenrick_extension_690mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 125, 'mpls_casement', 'casement_sash', 'Side Hung 957-1212mm Extensions',
  'is_opening and is_casement_mpls and is_side_hung and gross_sash_height_in_mm <= 1212 and gross_sash_height_in_mm >= 957',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_950mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 125
     AND product_short_name = 'kenrick_extension_950mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 130, 'mpls_casement', 'casement_sash', 'Side Hung 1213-1476 mm Extensions',
  'is_opening and is_casement_mpls and is_side_hung and gross_sash_height_in_mm <= 1476 and gross_sash_height_in_mm > 1214',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_1210mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 130
     AND product_short_name = 'kenrick_extension_1210mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 135, 'mpls_casement', 'casement_sash', 'Side Hung 1504mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 1476 and gross_sash_height_in_mm <= 1504',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 135
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 140, 'mpls_casement', 'casement_sash', 'Side Hung 1504mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 1476 and gross_sash_height_in_mm <= 1504',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_950mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 140
     AND product_short_name = 'kenrick_extension_950mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 145, 'mpls_casement', 'casement_sash', 'Side Hung 1505mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 1504 and gross_sash_height_in_mm <= 1770',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_490mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 145
     AND product_short_name = 'kenrick_extension_490mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 150, 'mpls_casement', 'casement_sash', 'Side Hung 1505mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 1504 and gross_sash_height_in_mm <= 1770',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 150
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 155, 'mpls_casement', 'casement_sash', 'Side Hung 1771mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 1771 and gross_sash_height_in_mm <= 2286',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_690mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 155
     AND product_short_name = 'kenrick_extension_690mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 160, 'mpls_casement', 'casement_sash', 'Side Hung 1771mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 1771 and gross_sash_height_in_mm <= 2286',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 160
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 165, 'mpls_casement', 'casement_sash', 'Side Hung 2798mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 2286 and gross_sash_height_in_mm <= 2798',
  '2', NULL, NULL, true,
  'default_ironmongery', 'kenrick_extension_1210mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 165
     AND product_short_name = 'kenrick_extension_1210mm'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 170, 'mpls_casement', 'casement_sash', 'Side Hung 2798mm Extensions',
  'is_opening and is_side_hung and is_casement_mpls and gross_sash_height_in_mm > 2286 and gross_sash_height_in_mm <= 2798',
  '1', NULL, NULL, true,
  'default_ironmongery', 'kenrick_excalibur_straight_extension_300mm', 'PC'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_casement' AND sort_order = 170
     AND product_short_name = 'kenrick_excalibur_straight_extension_300mm'
);

-- ---------------------------------------------------------------------------
-- GROUP: mpls_door
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 2, 'mpls_door', 'door_leaf', 'Standard Multipoint Lock French Door Euro Cylinder',
  'is_door_mpls and is_master_leaf_in_french_pair and not is_front_door',
  '1', NULL, NULL, true,
  'default_ironmongery', 'double_euro_cylinder', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_door' AND sort_order = 2
     AND product_short_name = 'double_euro_cylinder'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 3, 'mpls_door', 'door_leaf', 'Standard Multipoint Lock Euro Cylinder',
  'is_door_mpls and not is_front_door and not is_french_door_leaf',
  '1', NULL, NULL, true,
  'default_ironmongery', 'double_euro_cylinder', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_door' AND sort_order = 3
     AND product_short_name = 'double_euro_cylinder'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 5, 'mpls_door', 'door_leaf', 'Standard Handle',
  'is_door_mpls and frame_to_be_replaced and not is_front_door and not is_french_door_leaf',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_lyndon_door_espag_set', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_door' AND sort_order = 5
     AND product_short_name = 'hardwick_lyndon_door_espag_set'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 6, 'mpls_door', 'door_leaf', 'Standard Handle',
  'is_door_mpls and frame_to_be_replaced and not is_front_door and is_master_leaf_in_french_pair',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_lyndon_door_espag_set', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'mpls_door' AND sort_order = 6
     AND product_short_name = 'hardwick_lyndon_door_espag_set'
);

-- ---------------------------------------------------------------------------
-- GROUP: door_hinges
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'door_hinges', 'door_leaf', '4 Hinges per Door',
  'is_left_hand_hung_viewed_internally or is_right_hand_hung_viewed_internally',
  '2', NULL, NULL, true,
  'default_ironmongery', '102mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'door_hinges' AND sort_order = 10
     AND product_short_name = '102mm_hinges'
);

-- ---------------------------------------------------------------------------
-- GROUP: heritage_casement
-- ---------------------------------------------------------------------------
INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 10, 'heritage_casement', 'casement_sash', 'Heritage Range Hinges',
  'is_opening and is_heritage_range',
  '2', NULL, NULL, true,
  'default_ironmongery', '76mm_hinges', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'heritage_casement' AND sort_order = 10
     AND product_short_name = '76mm_hinges'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 20, 'heritage_casement', 'casement_sash', 'Heritage Range Hinges',
  'is_opening and is_heritage_range',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_lyndon_12_forged_casement_stay', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'heritage_casement' AND sort_order = 20
     AND product_short_name = 'hardwick_lyndon_12_forged_casement_stay'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 30, 'heritage_casement', 'casement_sash', 'Heritage Range Fastener',
  'is_opening and is_heritage_range and is_side_hung and is_left_hand_hung_viewed_internally',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_lyndon_lh_locking_nightvent_fastener', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'heritage_casement' AND sort_order = 30
     AND product_short_name = 'hardwick_lyndon_lh_locking_nightvent_fastener'
);

INSERT INTO part_allocation_rules
  (sort_order, group_name, loop_target, label, condition, qty_expr,
   part_code, measure_expr, is_active,
   rule_family, product_short_name, finish_code)
SELECT 35, 'heritage_casement', 'casement_sash', 'Heritage Range Fastener',
  'is_opening and is_heritage_range and is_side_hung and is_right_hand_hung_viewed_internally',
  '1', NULL, NULL, true,
  'default_ironmongery', 'hardwick_lyndon_rh_locking_nightvent_fastener', 'PB'
WHERE NOT EXISTS (
  SELECT 1 FROM part_allocation_rules
   WHERE rule_family = 'default_ironmongery'
     AND group_name = 'heritage_casement' AND sort_order = 35
     AND product_short_name = 'hardwick_lyndon_rh_locking_nightvent_fastener'
);

-- =============================================================================
-- VERIFICATION
-- =============================================================================

SELECT
  rule_family,
  group_name,
  is_active,
  count(*) AS rule_count
FROM part_allocation_rules
WHERE rule_family = 'default_ironmongery'
GROUP BY rule_family, group_name, is_active
ORDER BY group_name, is_active DESC;

COMMIT;
