-- ============================================================================
-- step-p4-validation-activate.sql
-- Activate validation rules that are unblocked by newly-added variables.
-- Apply through Supabase SQL Editor after step-p3.
-- Generated by manual analysis against computeVariables.js + computeQuoteVariables()
-- ============================================================================

-- ── Quote-level rules ────────────────────────────────────────────────────────

-- Rule 1: quote_margin now provided
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Reminder to Increase R Rumber in busy periods'
  AND condition LIKE '%quote_margin%'
  AND is_active = false;

-- Rule 2: item_qty, item_with_onsite_decoration_by_us_qty_excl_free_items, item_qty_with_solid_utile_hardwood_cill
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Single item fee'
  AND condition LIKE '%item_qty%'
  AND is_active = false;

-- Rule 3: spacer colour counts
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Mixed Spacer Colour'
  AND condition LIKE '%item_qty_with_black_warm_edge_spacer%'
  AND is_active = false;

-- Rule 4: spacer dimension counts
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Mixed Spacer Dimension'
  AND condition LIKE '%item_qty_with_4mm_spacer%'
  AND is_active = false;

-- Rule 5: cill material counts
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Cill Timber Not matching'
  AND condition LIKE '%item_qty_with_accoya_cill%'
  AND is_active = false;

-- Rule 6: item_installed_by_us_qty
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Installation labour hours'
  AND condition LIKE '%item_installed_by_us_qty%'
  AND is_active = false;

-- Rules 7-8: pricefile tracking (HQ)
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Quote PF not latest - HQ'
  AND condition LIKE '%quote_pricefile_no%'
  AND is_active = false;

UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Quote PF retired - HQ'
  AND condition LIKE '%is_pricefile_retired%'
  AND is_active = false;

-- Rules 9-10: pricefile tracking (restricted)
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Quote PF not latest - restricted'
  AND condition LIKE '%quote_pricefile_no%'
  AND is_active = false;

UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Quote PF retired - restricted'
  AND condition LIKE '%is_pricefile_retired%'
  AND is_active = false;

-- ── Item-level rules: Glass group ────────────────────────────────────────────

-- Rule 12: new_sash_with_curved_head_qty
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'No Curved Head Sash Replacements'
  AND condition LIKE '%new_sash_with_curved_head_qty%'
  AND is_active = false;

-- Rules 14 (Glass) and 115 (Recommendation): encapsulated_leaded_light_qty
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Encapsulated Leaded Lights'
  AND condition LIKE '%encapsulated_leaded_light_qty%'
  AND is_active = false;

-- Rule 15: glass_unit_thickness (Fineo Toughened Evacuation Port)
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Fineo Toughened Evacuation Port'
  AND condition LIKE '%glass_unit_thickness%'
  AND is_active = false;

-- ── Item-level rules: Sash Windows group ─────────────────────────────────────

-- Rule 31: 35mm Sashes DGU (blocked by glass_unit_thickness only)
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = '35mm Sashes DGU'
  AND condition LIKE '%glass_unit_thickness%'
  AND blocked_reason = 'missing variable: glass_unit_thickness'
  AND is_active = false;

-- Rules 37-38: 50mm Sashes DGU (blocked by glass_unit_thickness only)
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = '50mm Sashes DGU'
  AND condition LIKE '%glass_unit_thickness%'
  AND blocked_reason = 'missing variable: glass_unit_thickness'
  AND is_active = false;

-- Rule 39: Box Frame Depth
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Box Frame Depth'
  AND condition LIKE '%frame_depth%'
  AND is_active = false;

-- ── Item-level rules: Stormproof Casements group ─────────────────────────────

-- Rule 60: Casement Frame Thickness
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Casement Frame Thickness'
  AND condition LIKE '%frame_depth%'
  AND is_active = false;

-- ── Item-level rules: Missing Detail group ───────────────────────────────────

-- Rule 64: Frame depth 0
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Frame depth 0'
  AND condition LIKE '%frame_depth%'
  AND is_active = false;

-- Rule 65: Cill depth 0
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Cill depth 0'
  AND condition LIKE '%cill_depth%'
  AND is_active = false;

-- Rule 66: No surveyor
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'No surveyor'
  AND condition LIKE '%is_survey_drawing%'
  AND is_active = false;

-- Rules 68-69: surround_row_qty
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'No surrounds'
  AND condition LIKE '%surround_row_qty%'
  AND is_active = false;

UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Sash Replacement Surrounds'
  AND condition LIKE '%surround_row_qty%'
  AND is_active = false;

-- Rule 70: Unmodified default
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Unmodified default'
  AND condition LIKE '%has_unmodified_default_measurement%'
  AND is_active = false;

-- Rule 71: Paint empty
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Paint empty'
  AND condition LIKE '%internal_finish%'
  AND is_active = false;

-- ── Item-level rules: Dimension group ────────────────────────────────────────

-- Rule 76: Equal glazing is out
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Equal glazing is out'
  AND condition LIKE '%eq_glazing_is_out%'
  AND is_active = false;

-- Rule 77: Restricted sash travel
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Restricted sash travel'
  AND condition LIKE '%sliding_sash_with_restricted_travel_qty%'
  AND is_active = false;

-- Rule 80: Frame deeper than cill
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Frame deeper than cill'
  AND condition LIKE '%cill_height%'
  AND condition LIKE '%frame_depth%'
  AND is_active = false;

-- ── Item-level rules: Suspicious Detail group ────────────────────────────────

-- Rule 85: Oak
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Oak'
  AND condition LIKE '%is_oak_cill%'
  AND is_active = false;

-- Rule 86: Softwood Cill
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Softwood Cill'
  AND condition LIKE '%is_solid_redwood_cill%'
  AND is_active = false;

-- Rule 90: Single Glazed Item
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Single Glazed Item'
  AND condition LIKE '%glass_unit_thickness%'
  AND blocked_reason = 'missing variable: glass_unit_thickness'
  AND is_active = false;

-- Rule 91: DOCL Heritage
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'DOCL Heritage'
  AND condition LIKE '%glass_unit_qty%'
  AND condition LIKE '%glass_unit_thickness%'
  AND is_active = false;

-- Rule 92: DOCL Single
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'DOCL Single'
  AND condition LIKE '%glass_unit_qty%'
  AND condition LIKE '%glass_unit_thickness%'
  AND is_active = false;

-- ── Item-level rules: Recommendation group ───────────────────────────────────

-- Rule 103: Idigbo Warning
UPDATE public.validation_rules
SET is_active = true, blocked_reason = NULL
WHERE name = 'Idigbo Warning'
  AND condition LIKE '%is_idigbo_frame%'
  AND is_active = false;
